/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateKudoInput = {
  id?: string | null,
  giverId: string,
  receiverId: string,
  message: string,
  kudoVerb: KudoVerb,
  dataSourceApp: DataSourceApp,
  createdAt?: string | null,
  type?: string | null,
  link: string,
  metadata?: string | null,
};

export enum KudoVerb {
  kudos = "kudos",
  props = "props",
  sparkles = "sparkles",
  fireworks = "fireworks",
}


export enum DataSourceApp {
  github = "github",
  slack = "slack",
  teams = "teams",
  twitter = "twitter",
  other = "other",
}


export type ModelKudoConditionInput = {
  giverId?: ModelIDInput | null,
  receiverId?: ModelIDInput | null,
  message?: ModelStringInput | null,
  kudoVerb?: ModelKudoVerbInput | null,
  dataSourceApp?: ModelDataSourceAppInput | null,
  createdAt?: ModelStringInput | null,
  type?: ModelStringInput | null,
  link?: ModelStringInput | null,
  metadata?: ModelStringInput | null,
  and?: Array< ModelKudoConditionInput | null > | null,
  or?: Array< ModelKudoConditionInput | null > | null,
  not?: ModelKudoConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelKudoVerbInput = {
  eq?: KudoVerb | null,
  ne?: KudoVerb | null,
};

export type ModelDataSourceAppInput = {
  eq?: DataSourceApp | null,
  ne?: DataSourceApp | null,
};

export type Kudo = {
  __typename: "Kudo",
  id: string,
  giverId: string,
  receiverId: string,
  message: string,
  kudoVerb: KudoVerb,
  dataSourceApp: DataSourceApp,
  createdAt: string,
  type?: string | null,
  link: string,
  metadata?: string | null,
  giver?: Person | null,
  receiver?: Person | null,
  updatedAt: string,
};

export type Person = {
  __typename: "Person",
  id: string,
  username: string,
  email?: string | null,
  profileImageUrl?: string | null,
  dataSourceApp: DataSourceApp,
  kudosGiven?: ModelKudoConnection | null,
  kudosReceived?: ModelKudoConnection | null,
  createdAt: string,
  updatedAt: string,
};

export type ModelKudoConnection = {
  __typename: "ModelKudoConnection",
  items:  Array<Kudo | null >,
  nextToken?: string | null,
};

export type UpdateKudoInput = {
  id: string,
  giverId?: string | null,
  receiverId?: string | null,
  message?: string | null,
  kudoVerb?: KudoVerb | null,
  dataSourceApp?: DataSourceApp | null,
  createdAt?: string | null,
  type?: string | null,
  link?: string | null,
  metadata?: string | null,
};

export type DeleteKudoInput = {
  id: string,
};

export type CreatePersonInput = {
  id?: string | null,
  username: string,
  email?: string | null,
  profileImageUrl?: string | null,
  dataSourceApp: DataSourceApp,
};

export type ModelPersonConditionInput = {
  username?: ModelStringInput | null,
  email?: ModelStringInput | null,
  profileImageUrl?: ModelStringInput | null,
  dataSourceApp?: ModelDataSourceAppInput | null,
  and?: Array< ModelPersonConditionInput | null > | null,
  or?: Array< ModelPersonConditionInput | null > | null,
  not?: ModelPersonConditionInput | null,
};

export type UpdatePersonInput = {
  id: string,
  username?: string | null,
  email?: string | null,
  profileImageUrl?: string | null,
  dataSourceApp?: DataSourceApp | null,
};

export type DeletePersonInput = {
  id: string,
};

export type SearchableKudoFilterInput = {
  id?: SearchableIDFilterInput | null,
  giverId?: SearchableIDFilterInput | null,
  receiverId?: SearchableIDFilterInput | null,
  message?: SearchableStringFilterInput | null,
  createdAt?: SearchableStringFilterInput | null,
  type?: SearchableStringFilterInput | null,
  link?: SearchableStringFilterInput | null,
  metadata?: SearchableStringFilterInput | null,
  updatedAt?: SearchableStringFilterInput | null,
  kudoVerb?: SearchableStringFilterInput | null,
  dataSourceApp?: SearchableStringFilterInput | null,
  and?: Array< SearchableKudoFilterInput | null > | null,
  or?: Array< SearchableKudoFilterInput | null > | null,
  not?: SearchableKudoFilterInput | null,
};

export type SearchableIDFilterInput = {
  ne?: string | null,
  gt?: string | null,
  lt?: string | null,
  gte?: string | null,
  lte?: string | null,
  eq?: string | null,
  match?: string | null,
  matchPhrase?: string | null,
  matchPhrasePrefix?: string | null,
  multiMatch?: string | null,
  exists?: boolean | null,
  wildcard?: string | null,
  regexp?: string | null,
  range?: Array< string | null > | null,
};

export type SearchableStringFilterInput = {
  ne?: string | null,
  gt?: string | null,
  lt?: string | null,
  gte?: string | null,
  lte?: string | null,
  eq?: string | null,
  match?: string | null,
  matchPhrase?: string | null,
  matchPhrasePrefix?: string | null,
  multiMatch?: string | null,
  exists?: boolean | null,
  wildcard?: string | null,
  regexp?: string | null,
  range?: Array< string | null > | null,
};

export type SearchableKudoSortInput = {
  field?: SearchableKudoSortableFields | null,
  direction?: SearchableSortDirection | null,
};

export enum SearchableKudoSortableFields {
  id = "id",
  giverId = "giverId",
  receiverId = "receiverId",
  message = "message",
  createdAt = "createdAt",
  type = "type",
  link = "link",
  metadata = "metadata",
  updatedAt = "updatedAt",
}


export enum SearchableSortDirection {
  asc = "asc",
  desc = "desc",
}


export type SearchableKudoAggregationInput = {
  name: string,
  type: SearchableAggregateType,
  field: SearchableKudoAggregateField,
};

export enum SearchableAggregateType {
  terms = "terms",
  avg = "avg",
  min = "min",
  max = "max",
  sum = "sum",
}


export enum SearchableKudoAggregateField {
  id = "id",
  giverId = "giverId",
  receiverId = "receiverId",
  message = "message",
  kudoVerb = "kudoVerb",
  dataSourceApp = "dataSourceApp",
  createdAt = "createdAt",
  type = "type",
  link = "link",
  metadata = "metadata",
  updatedAt = "updatedAt",
}


export type SearchableKudoConnection = {
  __typename: "SearchableKudoConnection",
  items:  Array<Kudo | null >,
  nextToken?: string | null,
  total?: number | null,
  aggregateItems:  Array<SearchableAggregateResult | null >,
};

export type SearchableAggregateResult = {
  __typename: "SearchableAggregateResult",
  name: string,
  result?: SearchableAggregateGenericResult | null,
};

export type SearchableAggregateGenericResult = SearchableAggregateScalarResult | SearchableAggregateBucketResult


export type SearchableAggregateScalarResult = {
  __typename: "SearchableAggregateScalarResult",
  value: number,
};

export type SearchableAggregateBucketResult = {
  __typename: "SearchableAggregateBucketResult",
  buckets?:  Array<SearchableAggregateBucketResultItem | null > | null,
};

export type SearchableAggregateBucketResultItem = {
  __typename: "SearchableAggregateBucketResultItem",
  key: string,
  doc_count: number,
};

export type SearchablePersonFilterInput = {
  id?: SearchableIDFilterInput | null,
  username?: SearchableStringFilterInput | null,
  email?: SearchableStringFilterInput | null,
  profileImageUrl?: SearchableStringFilterInput | null,
  createdAt?: SearchableStringFilterInput | null,
  updatedAt?: SearchableStringFilterInput | null,
  dataSourceApp?: SearchableStringFilterInput | null,
  and?: Array< SearchablePersonFilterInput | null > | null,
  or?: Array< SearchablePersonFilterInput | null > | null,
  not?: SearchablePersonFilterInput | null,
};

export type SearchablePersonSortInput = {
  field?: SearchablePersonSortableFields | null,
  direction?: SearchableSortDirection | null,
};

export enum SearchablePersonSortableFields {
  id = "id",
  username = "username",
  email = "email",
  profileImageUrl = "profileImageUrl",
  createdAt = "createdAt",
  updatedAt = "updatedAt",
}


export type SearchablePersonAggregationInput = {
  name: string,
  type: SearchableAggregateType,
  field: SearchablePersonAggregateField,
};

export enum SearchablePersonAggregateField {
  id = "id",
  username = "username",
  email = "email",
  profileImageUrl = "profileImageUrl",
  dataSourceApp = "dataSourceApp",
  createdAt = "createdAt",
  updatedAt = "updatedAt",
}


export type SearchablePersonConnection = {
  __typename: "SearchablePersonConnection",
  items:  Array<Person | null >,
  nextToken?: string | null,
  total?: number | null,
  aggregateItems:  Array<SearchableAggregateResult | null >,
};

export type ModelKudoFilterInput = {
  id?: ModelIDInput | null,
  giverId?: ModelIDInput | null,
  receiverId?: ModelIDInput | null,
  message?: ModelStringInput | null,
  kudoVerb?: ModelKudoVerbInput | null,
  dataSourceApp?: ModelDataSourceAppInput | null,
  createdAt?: ModelStringInput | null,
  type?: ModelStringInput | null,
  link?: ModelStringInput | null,
  metadata?: ModelStringInput | null,
  and?: Array< ModelKudoFilterInput | null > | null,
  or?: Array< ModelKudoFilterInput | null > | null,
  not?: ModelKudoFilterInput | null,
};

export type ModelPersonFilterInput = {
  id?: ModelIDInput | null,
  username?: ModelStringInput | null,
  email?: ModelStringInput | null,
  profileImageUrl?: ModelStringInput | null,
  dataSourceApp?: ModelDataSourceAppInput | null,
  and?: Array< ModelPersonFilterInput | null > | null,
  or?: Array< ModelPersonFilterInput | null > | null,
  not?: ModelPersonFilterInput | null,
};

export type ModelPersonConnection = {
  __typename: "ModelPersonConnection",
  items:  Array<Person | null >,
  nextToken?: string | null,
};

export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type CreateKudoMutationVariables = {
  input: CreateKudoInput,
  condition?: ModelKudoConditionInput | null,
};

export type CreateKudoMutation = {
  createKudo?:  {
    __typename: "Kudo",
    id: string,
    giverId: string,
    receiverId: string,
    message: string,
    kudoVerb: KudoVerb,
    dataSourceApp: DataSourceApp,
    createdAt: string,
    type?: string | null,
    link: string,
    metadata?: string | null,
    giver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    receiver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    updatedAt: string,
  } | null,
};

export type UpdateKudoMutationVariables = {
  input: UpdateKudoInput,
  condition?: ModelKudoConditionInput | null,
};

export type UpdateKudoMutation = {
  updateKudo?:  {
    __typename: "Kudo",
    id: string,
    giverId: string,
    receiverId: string,
    message: string,
    kudoVerb: KudoVerb,
    dataSourceApp: DataSourceApp,
    createdAt: string,
    type?: string | null,
    link: string,
    metadata?: string | null,
    giver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    receiver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    updatedAt: string,
  } | null,
};

export type DeleteKudoMutationVariables = {
  input: DeleteKudoInput,
  condition?: ModelKudoConditionInput | null,
};

export type DeleteKudoMutation = {
  deleteKudo?:  {
    __typename: "Kudo",
    id: string,
    giverId: string,
    receiverId: string,
    message: string,
    kudoVerb: KudoVerb,
    dataSourceApp: DataSourceApp,
    createdAt: string,
    type?: string | null,
    link: string,
    metadata?: string | null,
    giver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    receiver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    updatedAt: string,
  } | null,
};

export type CreatePersonMutationVariables = {
  input: CreatePersonInput,
  condition?: ModelPersonConditionInput | null,
};

export type CreatePersonMutation = {
  createPerson?:  {
    __typename: "Person",
    id: string,
    username: string,
    email?: string | null,
    profileImageUrl?: string | null,
    dataSourceApp: DataSourceApp,
    kudosGiven?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    kudosReceived?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdatePersonMutationVariables = {
  input: UpdatePersonInput,
  condition?: ModelPersonConditionInput | null,
};

export type UpdatePersonMutation = {
  updatePerson?:  {
    __typename: "Person",
    id: string,
    username: string,
    email?: string | null,
    profileImageUrl?: string | null,
    dataSourceApp: DataSourceApp,
    kudosGiven?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    kudosReceived?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeletePersonMutationVariables = {
  input: DeletePersonInput,
  condition?: ModelPersonConditionInput | null,
};

export type DeletePersonMutation = {
  deletePerson?:  {
    __typename: "Person",
    id: string,
    username: string,
    email?: string | null,
    profileImageUrl?: string | null,
    dataSourceApp: DataSourceApp,
    kudosGiven?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    kudosReceived?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type SearchKudosQueryVariables = {
  filter?: SearchableKudoFilterInput | null,
  sort?: Array< SearchableKudoSortInput | null > | null,
  limit?: number | null,
  nextToken?: string | null,
  from?: number | null,
  aggregates?: Array< SearchableKudoAggregationInput | null > | null,
};

export type SearchKudosQuery = {
  searchKudos?:  {
    __typename: "SearchableKudoConnection",
    items:  Array< {
      __typename: "Kudo",
      id: string,
      giverId: string,
      receiverId: string,
      message: string,
      kudoVerb: KudoVerb,
      dataSourceApp: DataSourceApp,
      createdAt: string,
      type?: string | null,
      link: string,
      metadata?: string | null,
      giver?:  {
        __typename: "Person",
        id: string,
        username: string,
        email?: string | null,
        profileImageUrl?: string | null,
        dataSourceApp: DataSourceApp,
        kudosGiven?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        kudosReceived?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      receiver?:  {
        __typename: "Person",
        id: string,
        username: string,
        email?: string | null,
        profileImageUrl?: string | null,
        dataSourceApp: DataSourceApp,
        kudosGiven?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        kudosReceived?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
    total?: number | null,
    aggregateItems:  Array< {
      __typename: "SearchableAggregateResult",
      name: string,
      result: ( {
          __typename: "SearchableAggregateScalarResult",
          value: number,
        } | {
          __typename: "SearchableAggregateBucketResult",
          buckets?:  Array< {
            __typename: string,
            key: string,
            doc_count: number,
          } | null > | null,
        }
      ) | null,
    } | null >,
  } | null,
};

export type SearchPeopleQueryVariables = {
  filter?: SearchablePersonFilterInput | null,
  sort?: Array< SearchablePersonSortInput | null > | null,
  limit?: number | null,
  nextToken?: string | null,
  from?: number | null,
  aggregates?: Array< SearchablePersonAggregationInput | null > | null,
};

export type SearchPeopleQuery = {
  searchPeople?:  {
    __typename: "SearchablePersonConnection",
    items:  Array< {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
    total?: number | null,
    aggregateItems:  Array< {
      __typename: "SearchableAggregateResult",
      name: string,
      result: ( {
          __typename: "SearchableAggregateScalarResult",
          value: number,
        } | {
          __typename: "SearchableAggregateBucketResult",
          buckets?:  Array< {
            __typename: string,
            key: string,
            doc_count: number,
          } | null > | null,
        }
      ) | null,
    } | null >,
  } | null,
};

export type GetKudoQueryVariables = {
  id: string,
};

export type GetKudoQuery = {
  getKudo?:  {
    __typename: "Kudo",
    id: string,
    giverId: string,
    receiverId: string,
    message: string,
    kudoVerb: KudoVerb,
    dataSourceApp: DataSourceApp,
    createdAt: string,
    type?: string | null,
    link: string,
    metadata?: string | null,
    giver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    receiver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    updatedAt: string,
  } | null,
};

export type ListKudosQueryVariables = {
  filter?: ModelKudoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListKudosQuery = {
  listKudos?:  {
    __typename: "ModelKudoConnection",
    items:  Array< {
      __typename: "Kudo",
      id: string,
      giverId: string,
      receiverId: string,
      message: string,
      kudoVerb: KudoVerb,
      dataSourceApp: DataSourceApp,
      createdAt: string,
      type?: string | null,
      link: string,
      metadata?: string | null,
      giver?:  {
        __typename: "Person",
        id: string,
        username: string,
        email?: string | null,
        profileImageUrl?: string | null,
        dataSourceApp: DataSourceApp,
        kudosGiven?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        kudosReceived?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      receiver?:  {
        __typename: "Person",
        id: string,
        username: string,
        email?: string | null,
        profileImageUrl?: string | null,
        dataSourceApp: DataSourceApp,
        kudosGiven?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        kudosReceived?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetPersonQueryVariables = {
  id: string,
};

export type GetPersonQuery = {
  getPerson?:  {
    __typename: "Person",
    id: string,
    username: string,
    email?: string | null,
    profileImageUrl?: string | null,
    dataSourceApp: DataSourceApp,
    kudosGiven?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    kudosReceived?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListPeopleQueryVariables = {
  filter?: ModelPersonFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPeopleQuery = {
  listPeople?:  {
    __typename: "ModelPersonConnection",
    items:  Array< {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type KudosByDateQueryVariables = {
  type: string,
  createdAt?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelKudoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type KudosByDateQuery = {
  kudosByDate?:  {
    __typename: "ModelKudoConnection",
    items:  Array< {
      __typename: "Kudo",
      id: string,
      giverId: string,
      receiverId: string,
      message: string,
      kudoVerb: KudoVerb,
      dataSourceApp: DataSourceApp,
      createdAt: string,
      type?: string | null,
      link: string,
      metadata?: string | null,
      giver?:  {
        __typename: "Person",
        id: string,
        username: string,
        email?: string | null,
        profileImageUrl?: string | null,
        dataSourceApp: DataSourceApp,
        kudosGiven?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        kudosReceived?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      receiver?:  {
        __typename: "Person",
        id: string,
        username: string,
        email?: string | null,
        profileImageUrl?: string | null,
        dataSourceApp: DataSourceApp,
        kudosGiven?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        kudosReceived?:  {
          __typename: "ModelKudoConnection",
          nextToken?: string | null,
        } | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateKudoSubscription = {
  onCreateKudo?:  {
    __typename: "Kudo",
    id: string,
    giverId: string,
    receiverId: string,
    message: string,
    kudoVerb: KudoVerb,
    dataSourceApp: DataSourceApp,
    createdAt: string,
    type?: string | null,
    link: string,
    metadata?: string | null,
    giver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    receiver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    updatedAt: string,
  } | null,
};

export type OnUpdateKudoSubscription = {
  onUpdateKudo?:  {
    __typename: "Kudo",
    id: string,
    giverId: string,
    receiverId: string,
    message: string,
    kudoVerb: KudoVerb,
    dataSourceApp: DataSourceApp,
    createdAt: string,
    type?: string | null,
    link: string,
    metadata?: string | null,
    giver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    receiver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    updatedAt: string,
  } | null,
};

export type OnDeleteKudoSubscription = {
  onDeleteKudo?:  {
    __typename: "Kudo",
    id: string,
    giverId: string,
    receiverId: string,
    message: string,
    kudoVerb: KudoVerb,
    dataSourceApp: DataSourceApp,
    createdAt: string,
    type?: string | null,
    link: string,
    metadata?: string | null,
    giver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    receiver?:  {
      __typename: "Person",
      id: string,
      username: string,
      email?: string | null,
      profileImageUrl?: string | null,
      dataSourceApp: DataSourceApp,
      kudosGiven?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      kudosReceived?:  {
        __typename: "ModelKudoConnection",
        items:  Array< {
          __typename: "Kudo",
          id: string,
          giverId: string,
          receiverId: string,
          message: string,
          kudoVerb: KudoVerb,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          type?: string | null,
          link: string,
          metadata?: string | null,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    updatedAt: string,
  } | null,
};

export type OnCreatePersonSubscription = {
  onCreatePerson?:  {
    __typename: "Person",
    id: string,
    username: string,
    email?: string | null,
    profileImageUrl?: string | null,
    dataSourceApp: DataSourceApp,
    kudosGiven?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    kudosReceived?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdatePersonSubscription = {
  onUpdatePerson?:  {
    __typename: "Person",
    id: string,
    username: string,
    email?: string | null,
    profileImageUrl?: string | null,
    dataSourceApp: DataSourceApp,
    kudosGiven?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    kudosReceived?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeletePersonSubscription = {
  onDeletePerson?:  {
    __typename: "Person",
    id: string,
    username: string,
    email?: string | null,
    profileImageUrl?: string | null,
    dataSourceApp: DataSourceApp,
    kudosGiven?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    kudosReceived?:  {
      __typename: "ModelKudoConnection",
      items:  Array< {
        __typename: "Kudo",
        id: string,
        giverId: string,
        receiverId: string,
        message: string,
        kudoVerb: KudoVerb,
        dataSourceApp: DataSourceApp,
        createdAt: string,
        type?: string | null,
        link: string,
        metadata?: string | null,
        giver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        receiver?:  {
          __typename: "Person",
          id: string,
          username: string,
          email?: string | null,
          profileImageUrl?: string | null,
          dataSourceApp: DataSourceApp,
          createdAt: string,
          updatedAt: string,
        } | null,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
